/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;  
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.io.*;



/**
 *
 * @author User
 */
public class Hotel extends javax.swing.JFrame {
int FASILITAS1,FASILITAS2,Biaya,TOTAL,TOTAL2,Kembali,Lama,Harga,BiayaSewa,bayar;
    
String CEKIN;
String CEKOUT;
    

    

    /**
     * Creates new form Hotel
     */
    public Hotel() {
        initComponents();
        setTitle("Production by Rika");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cekTgl = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jLabel55 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jenisPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bodypanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnPesan = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        InfoKamar = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        PesanPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        cmbKode = new javax.swing.JComboBox<>();
        txtKamar = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        txtHarga = new javax.swing.JTextField();
        txtCekin = new javax.swing.JTextField();
        txtCekout = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtLamaMeng = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Cbfas1 = new javax.swing.JCheckBox();
        Cbfas2 = new javax.swing.JCheckBox();
        txtHarga1 = new javax.swing.JTextField();
        txtHarga2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtBiayaSewa = new javax.swing.JTextField();
        txtFasTam = new javax.swing.JTextField();
        txtTotalSewa = new javax.swing.JTextField();
        txtBayar = new javax.swing.JTextField();
        txtKembali = new javax.swing.JTextField();
        btnCek = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        jLabel64 = new javax.swing.JLabel();
        txtNoHp = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        HomePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        jLabel27.setText("jLabel27");

        cekTgl.setText("CEK");
        cekTgl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekTglActionPerformed(evt);
            }
        });

        jMenu1.setText("jMenu1");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("2. Deluxe Room ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("2. Deluxe Room ");

        jenisPanel.setBackground(new java.awt.Color(51, 255, 51));
        jenisPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 204));
        jLabel7.setText("1. Standard Room  ");

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel30.setText("M101 = Rp. 80.000");

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel31.setText("M102 = Rp. 85.000");

        jLabel32.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel32.setText("M103 = Rp. 90.000");

        jLabel33.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel33.setText("M104 = Rp. 95.000");

        jLabel34.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel34.setText("N201 = Rp. 100.000");

        jLabel35.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel35.setText("N202 = Rp.150.000");

        jLabel36.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel36.setText("N203 =Rp. 200.000");

        jLabel37.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel37.setText("N204 = Rp. 250.000");

        javax.swing.GroupLayout jenisPanelLayout = new javax.swing.GroupLayout(jenisPanel);
        jenisPanel.setLayout(jenisPanelLayout);
        jenisPanelLayout.setHorizontalGroup(
            jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisPanelLayout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31))
                    .addComponent(jLabel30)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(jLabel7))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jenisPanelLayout.setVerticalGroup(
            jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jenisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jenisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jenisPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel29))
                    .addGroup(jenisPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addGap(38, 38, 38))
        );

        jPanel3.setBackground(new java.awt.Color(51, 255, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(0, 0, 204));
        jLabel46.setText("2. Deluxe Room ");

        jLabel47.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel47.setText("M101 = Rp. 255.000");

        jLabel48.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel48.setText("M102 = Rp. 260.000");

        jLabel49.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel49.setText("M103 = Rp. 270.000");

        jLabel50.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel50.setText("M104 = Rp. 275.000");

        jLabel51.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel51.setText("N201 = Rp. 280.000");

        jLabel52.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel52.setText("N202 = Rp.300.000");

        jLabel53.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel53.setText("N203 =Rp. 310.000");

        jLabel54.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel54.setText("N204 = Rp. 350.000");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46)
                    .addComponent(jLabel47)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49)
                    .addComponent(jLabel50)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel53)
                    .addComponent(jLabel54))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel50)
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel53)
                .addGap(18, 18, 18)
                .addComponent(jLabel54)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setText("jLabel9");

        bodypanel.setBackground(new java.awt.Color(0, 204, 204));

        menuPanel.setBackground(new java.awt.Color(0, 204, 204));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHome.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\button-home-p1.jpg")); // NOI18N
        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnPesan.setBackground(new java.awt.Color(255, 255, 255));
        btnPesan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPesan.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\button-pesan-p.jpg")); // NOI18N
        btnPesan.setText("Pesan");
        btnPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\button-exit-p.jpg")); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setText("Welcome to");

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel2.setText("the Hotel");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel3.setText("Reservation");

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\hotel frozen.jpg")); // NOI18N
        jLabel12.setText("jLabel12");

        InfoKamar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        InfoKamar.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\icon info2.png")); // NOI18N
        InfoKamar.setText("Info Kamar");
        InfoKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoKamarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(InfoKamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap())
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(51, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        mainPanel.setLayout(new java.awt.CardLayout());

        PesanPanel.setBackground(new java.awt.Color(0, 204, 255));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("MENU - PESAN");

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("NAMA PELANGGAN");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("KODE KAMAR");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("NAMA KAMAR");

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TIPE KAMAR");

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("HARGA KAMAR");

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CEK IN");

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CEK OUT");

        cmbKode.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbKode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---pilihan---", "M101", "M102", "M103", "M104", "N201", "N202", "N203", "N204" }));
        cmbKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKodeActionPerformed(evt);
            }
        });

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton1.setText("Standard");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton2.setText("Deluxe");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton3.setText("Suite");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        txtCekin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCekinActionPerformed(evt);
            }
        });
        txtCekin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtCekinPropertyChange(evt);
            }
        });

        txtCekout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCekoutActionPerformed(evt);
            }
        });
        txtCekout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCekoutKeyReleased(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("LAMA MENGINAP");

        txtLamaMeng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLamaMengActionPerformed(evt);
            }
        });
        txtLamaMeng.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLamaMengKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setText("FASILITAS TAMBAHAN");

        Cbfas1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cbfas1.setText("TELEVISI");
        Cbfas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbfas1ActionPerformed(evt);
            }
        });

        Cbfas2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cbfas2.setText("WIFI");
        Cbfas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbfas2ActionPerformed(evt);
            }
        });

        txtHarga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHarga1ActionPerformed(evt);
            }
        });

        txtHarga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHarga2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("BIAYA SEWA");

        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("FASILITAS TAMBAHAN");

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("TOTAL SEWA");

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("BAYAR");

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("KEMBALI");

        txtBiayaSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBiayaSewaActionPerformed(evt);
            }
        });

        txtFasTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFasTamActionPerformed(evt);
            }
        });
        txtFasTam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFasTamKeyReleased(evt);
            }
        });

        btnCek.setBackground(new java.awt.Color(204, 0, 204));
        btnCek.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCek.setText("CEK");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFasTam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBiayaSewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalSewa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCek)
                                .addGap(25, 25, 25)))
                        .addGap(66, 66, 66))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBiayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtFasTam, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        btnHitung.setBackground(new java.awt.Color(153, 0, 153));
        btnHitung.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 0, 153));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setText("HARI");

        btnCetak.setBackground(new java.awt.Color(204, 0, 204));
        btnCetak.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        jLabel64.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("NO. HP");

        btnOK.setBackground(new java.awt.Color(204, 0, 204));
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButton4.setText("Precident ");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ALAMAT");

        javax.swing.GroupLayout PesanPanelLayout = new javax.swing.GroupLayout(PesanPanel);
        PesanPanel.setLayout(PesanPanelLayout);
        PesanPanelLayout.setHorizontalGroup(
            PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(PesanPanelLayout.createSequentialGroup()
                                .addComponent(Cbfas2)
                                .addGap(79, 79, 79)
                                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHarga1)
                                    .addComponent(txtHarga2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PesanPanelLayout.createSequentialGroup()
                                    .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel16))
                                    .addGap(33, 33, 33))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)))
                            .addGroup(PesanPanelLayout.createSequentialGroup()
                                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel64)
                                    .addComponent(jLabel6))
                                .addGap(102, 102, 102)))
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PesanPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jRadioButton1)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton3)
                                .addGap(10, 10, 10)
                                .addComponent(jRadioButton4))
                            .addGroup(PesanPanelLayout.createSequentialGroup()
                                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbKode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNoHp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txtKamar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                    .addComponent(txtCekin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCekout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PesanPanelLayout.createSequentialGroup()
                                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnOK)
                                            .addComponent(txtLamaMeng, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel28)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(Cbfas1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addComponent(btnClear)
                        .addGap(66, 66, 66)
                        .addComponent(btnCetak)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PesanPanelLayout.createSequentialGroup()
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHitung)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94))))
        );
        PesanPanelLayout.setVerticalGroup(
            PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PesanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PesanPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel64)
                            .addComponent(txtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(cmbKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton4))
                        .addGap(18, 18, 18)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtCekin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCekout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLamaMeng, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOK)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PesanPanelLayout.createSequentialGroup()
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(btnHitung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cbfas1)
                            .addComponent(txtHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbfas2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PesanPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(PesanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnCetak))))
                .addGap(69, 69, Short.MAX_VALUE))
        );

        mainPanel.add(PesanPanel, "card3");

        HomePanel.setBackground(new java.awt.Color(0, 204, 204));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\Ilustrasi-hotel4.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainPanel.add(HomePanel, "card2");

        javax.swing.GroupLayout bodypanelLayout = new javax.swing.GroupLayout(bodypanel);
        bodypanel.setLayout(bodypanelLayout);
        bodypanelLayout.setHorizontalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 888, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bodypanelLayout.setVerticalGroup(
            bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodypanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodypanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bodypanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodypanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        // remove panel
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        mainPanel.add(HomePanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanActionPerformed
        // TODO add your handling code here:
        
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
        
        // add panel
        mainPanel.add(PesanPanel);
        mainPanel.repaint();
        mainPanel.revalidate();
    }//GEN-LAST:event_btnPesanActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,  " Apakah Anda Yakin Ingin Keluar", "PERINGATAN",dialogBtn);
        if (dialogResult == 0) {
            //true condition
          System.exit(0);  
        }else {
            //false condition
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
         if (cmbKode.getSelectedItem().equals("M101")) {
        Biaya=350000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M102")) {
        Biaya =355000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M103")) {
        Biaya = 360000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M104")) {
        Biaya = 365000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N201")) {
        Biaya=370000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N202")) {
        Biaya =375000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N203")) {
        Biaya = 400000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N204")) {
        Biaya = 450000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
                                                                                       

    }                                            
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void cmbKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKodeActionPerformed
        // TODO add your handling code here:
        if (cmbKode.getSelectedItem().equals("M101")) {
            txtKamar.setText("SINGLE BAD");
        }else if (cmbKode.getSelectedItem().equals("M102")) {
            txtKamar.setText("SINGLE BAD");
        }else if (cmbKode.getSelectedItem().equals("M103")) {
            txtKamar.setText("SINGLE BAD");
        }else if (cmbKode.getSelectedItem().equals("M104")) {
            txtKamar.setText("SINGLE BAD");
        }else if (cmbKode.getSelectedItem().equals("N201")) {
            txtKamar.setText("DOUBLE BAD");
        }else if (cmbKode.getSelectedItem().equals("N202")) {
            txtKamar.setText("DOUBLE BAD");
        }else if (cmbKode.getSelectedItem().equals("N203")) {
            txtKamar.setText("DOUBLE BAD");
        }else if (cmbKode.getSelectedItem().equals("N204")) {
            txtKamar.setText("DOUBLE BAD");
        }
    }//GEN-LAST:event_cmbKodeActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        if (cmbKode.getSelectedItem().equals("M101")) {
        Biaya=80000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M102")) {
        Biaya =85000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M103")) {
        Biaya =90000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M104")) {
        Biaya =95000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N201")) {
        Biaya=100000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N202")) {
        Biaya =150000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N203")) {
        Biaya =200000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N204")) {
        Biaya =250000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    if (cmbKode.getSelectedItem().equals("M101")) {
        Biaya=255000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M102")) {
        Biaya =260000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M103")) {
        Biaya = 270000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M104")) {
        Biaya = 275000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N201")) {
        Biaya=280000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N202")) {
        Biaya =300000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N203")) {
        Biaya = 310000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N204")) {
        Biaya = 350000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
    
    }                                             
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        if (cmbKode.getSelectedItem().equals("M101")) {
        Biaya=300000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M102")) {
        Biaya =310000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M103")) {
        Biaya = 315000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("M104")) {
        Biaya = 320000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N201")) {
        Biaya=325000;
        TOTAL=Biaya;   
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N202")) {
        Biaya =330000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N203")) {
        Biaya = 350000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
        }else if (cmbKode.getSelectedItem().equals("N204")) {
        Biaya = 400000;
        TOTAL = Biaya;
        txtHarga.setText(String.valueOf(TOTAL));
                                                
    }                                             

    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void txtCekoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCekoutActionPerformed
        // TODO add your handling code here:
                 DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try{
            
            //Konversi dari string ke tanggal
           Date TanggalCEKIN =df.parse(txtCekin.getText());
           Date TanggalCEKOUT = df.parse(txtCekout.getText());
            
            //Tgl di konversi ke milidetik
            long Hari1 = TanggalCEKIN.getTime();
            long Hari2 = TanggalCEKOUT.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            txtLamaMeng.setText(Long.toString(Lama));
            
            
        } catch (ParseException e)
        {
        e.printStackTrace();
      }
    }//GEN-LAST:event_txtCekoutActionPerformed

    private void txtHarga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHarga1ActionPerformed
        // TODO add your handling code here:
        if(Cbfas1.isSelected()){
           FASILITAS1=200000;
           txtHarga1.setText(String.valueOf(FASILITAS1));
           TOTAL=FASILITAS1+FASILITAS2;
           txtFasTam.setText(String.valueOf(TOTAL));
        }else {
            FASILITAS1=0;
            txtHarga1.setText(String.valueOf(FASILITAS1));
            TOTAL=FASILITAS1+FASILITAS2;
            TOTAL2=Biaya+FASILITAS1+FASILITAS2;
            txtFasTam.setText(String.valueOf(TOTAL));
        }
    }//GEN-LAST:event_txtHarga1ActionPerformed

    private void txtHarga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHarga2ActionPerformed
        // TODO add your handling code here:
          if(Cbfas2.isSelected()){
           FASILITAS2=400000;
           txtHarga2.setText(String.valueOf(FASILITAS2));
           TOTAL=FASILITAS1+FASILITAS2;
           txtFasTam.setText(String.valueOf(TOTAL));
        }else {
            FASILITAS1=0;
            txtHarga2.setText(String.valueOf(FASILITAS2));
            TOTAL=FASILITAS1+FASILITAS2;
            txtFasTam.setText(String.valueOf(TOTAL));
          }
    }//GEN-LAST:event_txtHarga2ActionPerformed

    private void txtLamaMengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLamaMengActionPerformed
        // TODO add your handling code here:
        Lama=Integer.parseInt(txtLamaMeng.getText());
        Harga=Integer.parseInt(txtHarga.getText());
        TOTAL=bayar*Harga;
        txtBiayaSewa.setText(String.valueOf(TOTAL));
        
    }//GEN-LAST:event_txtLamaMengActionPerformed

    private void txtFasTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFasTamActionPerformed
        // TODO add your handling code here:
        int fasilitas=Integer.parseInt(txtFasTam.getText());
        int biaya=Integer.parseInt(txtBiayaSewa.getText());
        int hasil2=fasilitas+biaya;
        txtTotalSewa.setText(""+hasil2);
    }//GEN-LAST:event_txtFasTamActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        int bayar=Integer.parseInt(txtBayar.getText());
        int bayar1=Integer.parseInt( txtTotalSewa.getText());
        int kembali=bayar-bayar1;
        txtKembali.setText(""+kembali);
        
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtKamar.setText("");
        txtHarga.setText("");
        txtCekout.setText("");
        txtCekin.setText("");
        txtLamaMeng.setText("");
        txtTotalSewa.setText("");
        txtKembali.setText("");
        txtBayar.setText("");
        txtBiayaSewa.setText("");
        txtHarga1.setText("");
        txtHarga2.setText("");
        txtFasTam.setText("");
        txtNoHp.setText("");
        txtAlamat.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void Cbfas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbfas1ActionPerformed
        // TODO add your handling code here:
        if(Cbfas1.isSelected()){
           FASILITAS1=200000;
           txtHarga1.setText(String.valueOf(FASILITAS1));
           TOTAL=FASILITAS1+FASILITAS2;
           txtFasTam.setText(String.valueOf(TOTAL));
        }else {
            FASILITAS1=0;
            txtHarga1.setText(String.valueOf(FASILITAS1));
            TOTAL=FASILITAS1+FASILITAS2;
            TOTAL2=Biaya+FASILITAS1+FASILITAS2;
            txtFasTam.setText(String.valueOf(TOTAL));
        }
                                 
    }//GEN-LAST:event_Cbfas1ActionPerformed

    private void Cbfas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbfas2ActionPerformed
        // TODO add your handling code here:
        if(Cbfas2.isSelected()){
           FASILITAS2=400000;
           txtHarga2.setText(String.valueOf(FASILITAS2));
           TOTAL=FASILITAS1+FASILITAS2;
           txtFasTam.setText(String.valueOf(TOTAL));
        }else {
            FASILITAS1=0;
            txtHarga2.setText(String.valueOf(FASILITAS2));
            TOTAL=FASILITAS1+FASILITAS2;
            txtFasTam.setText(String.valueOf(TOTAL));
          }
    }//GEN-LAST:event_Cbfas2ActionPerformed

    private void txtCekinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtCekinPropertyChange
        // TODO add your handling code
       
    }//GEN-LAST:event_txtCekinPropertyChange

    private void txtBiayaSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBiayaSewaActionPerformed
        // TODO add your handling code here:
        int X=Integer.parseInt(txtHarga.getText());
        int Y=Integer.parseInt(txtLamaMeng.getText());
        int hasil=X * Y;
        txtBiayaSewa.setText(""+hasil);
    }//GEN-LAST:event_txtBiayaSewaActionPerformed

    private void cekTglActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekTglActionPerformed
        // TODO add your handling code here:
         DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try{
            
            //Konversi dari string ke tanggal
           Date TanggalCEKIN =df.parse(txtCekin.getText());
           Date TanggalCEKOUT = df.parse(txtCekout.getText());
            
            //Tgl di konversi ke milidetik
            long Hari1 = TanggalCEKIN.getTime();
            long Hari2 = TanggalCEKOUT.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            txtLamaMeng.setText(Long.toString(Lama));
            
            
        } catch (ParseException e)
        {
        e.printStackTrace();
        }
    }//GEN-LAST:event_cekTglActionPerformed

    private void txtLamaMengKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLamaMengKeyReleased
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtHarga.getText());
        b=Integer.valueOf(txtLamaMeng.getText());
        c=a*b;
        txtBiayaSewa.setText(""+c);
    }//GEN-LAST:event_txtLamaMengKeyReleased

    private void txtCekoutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCekoutKeyReleased
        // TODO add your handling code here:
            DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try{
            
            //Konversi dari string ke tanggal
           Date TanggalCEKIN =df.parse(txtCekin.getText());
           Date TanggalCEKOUT = df.parse(txtCekout.getText());
            
            //Tgl di konversi ke milidetik
            long Hari1 = TanggalCEKIN.getTime();
            long Hari2 = TanggalCEKOUT.getTime();
            long diff = Hari2 - Hari1;
            long Lama = diff / (24 * 60 * 60 * 1000);
            txtLamaMeng.setText(Long.toString(Lama));
            
            
        } catch (ParseException e)
        {
        e.printStackTrace();
      }
    }//GEN-LAST:event_txtCekoutKeyReleased

    private void txtFasTamKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFasTamKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txtBiayaSewa.getText());
        b=Integer.valueOf(txtFasTam.getText());
        c=a+b;
        txtTotalSewa.setText(""+c);
    }//GEN-LAST:event_txtFasTamKeyReleased

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(txtBiayaSewa.getText());
        b=Integer.valueOf(txtFasTam.getText());
        c=a+b;
        txtTotalSewa.setText(""+c);
    }//GEN-LAST:event_btnCekActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(null, "Struk Pembayaran Anda:"
                
                
                +"\n Nama Pelanggan            :"+txtNama.getText()
                +"\n No. Hp                    :"+txtNoHp.getText()
                +"\n Alamat                    :"+txtAlamat.getText()
                +"\n Kode Kamar                :"+cmbKode.getSelectedItem()
                +"\n Nama Kamar                :"+txtKamar.getText()
                +"\n Harga Kamar               :"+txtHarga.getText()
                +"\n Tanggal Cek  in           :"+txtCekin.getText()
                +"\n Tanggal Cek  Out          :"+txtCekin.getText()
                +"\n Lama Menginap             :"+txtLamaMeng.getText() + " Hari "
                +"\n Biaya Sewa                :"+txtBiayaSewa.getText()
                +"\n Fasilitas Televisi        :"+txtHarga1.getText()
                +"\n Fasilitas Wifi            :"+txtHarga2.getText()
                +"\n Jumlah Fasilitas Tambahan :"+txtFasTam.getText()
                +"\n Total Sewa                :"+txtTotalSewa.getText()
                +"\n Bayar                     :"+txtBayar.getText()
                +"\n Uang Kembali              :"+txtKembali.getText()
                ,"",JOptionPane.INFORMATION_MESSAGE);
               
    }//GEN-LAST:event_btnCetakActionPerformed

    private void InfoKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoKamarActionPerformed
        // TODO add your handling code here:
        Info_Kamar n = new Info_Kamar();
        n.setVisible(true);
        
    }//GEN-LAST:event_InfoKamarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        int a, b, c;
        a=Integer.valueOf(txtHarga.getText());
        b=Integer.valueOf(txtLamaMeng.getText());
        c=a*b;
        txtBiayaSewa.setText(""+c);
    
    }//GEN-LAST:event_btnOKActionPerformed

    private void txtCekinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCekinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCekinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Cbfas1;
    private javax.swing.JCheckBox Cbfas2;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton InfoKamar;
    private javax.swing.JPanel PesanPanel;
    private javax.swing.JPanel bodypanel;
    private javax.swing.JButton btnCek;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnPesan;
    private javax.swing.JButton cekTgl;
    private javax.swing.JComboBox<String> cmbKode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JPanel jenisPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtBayar;
    private javax.swing.JTextField txtBiayaSewa;
    private javax.swing.JTextField txtCekin;
    private javax.swing.JTextField txtCekout;
    private javax.swing.JTextField txtFasTam;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHarga1;
    private javax.swing.JTextField txtHarga2;
    private javax.swing.JTextField txtKamar;
    private javax.swing.JTextField txtKembali;
    private javax.swing.JTextField txtLamaMeng;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JTextField txtTotalSewa;
    // End of variables declaration//GEN-END:variables
}
